[package]
name = "relay"
version = "0.1.1"
description = "A HTTP request-response relay used by Hoppscotch Desktop and Hoppscotch Agent for more advanced request handling including custom headers, certificates, proxies, and local system integration."
authors = ["CuriousCorrelation"]
edition = "2021"

[dependencies]
curl = { git = "https://github.com/CuriousCorrelation/curl-rust.git", features = ["ntlm"] }
tokio-util = "0.7.12"
lazy_static = "1.5.0"
time = { version = "0.3.37", features = ["serde"] }
openssl = { version = "0.10.66", features = ["vendored"] }
# NOTE: This crate follows `openssl-sys` from https://github.com/CuriousCorrelation/curl-rust.git
# to avoid issues from version mismatch when compiling from source.
openssl-sys = { version = "0.9.64", features = ["vendored"] }
log = "0.4.22"
env_logger = "0.11.5"
thiserror = "1.0.64"
http = "1.1.0"
http-serde = "2.1.1"
url-escape = "0.1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "2.1.3"
dashmap = "6.1.0"
tracing = "0.1.41"
infer = "0.16.0"
strum = { version = "0.26.3", features = ["derive"] }
bytes = { version = "1.9.0", features = ["serde"] }
mime = "0.3.17"
url = "2.5.4"
