export enum InfraConfigEnum {
  MAILER_SMTP_ENABLE = 'MAILER_SMTP_ENABLE',
  MAILER_USE_CUSTOM_CONFIGS = 'MAILER_USE_CUSTOM_CONFIGS',
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  MAILER_SMTP_HOST = 'MAILER_SMTP_HOST',
  MAILER_SMTP_PORT = 'MAILER_SMTP_PORT',
  MAILER_SMTP_SECURE = 'MAILER_SMTP_SECURE',
  MAILER_SMTP_USER = 'MAILER_SMTP_USER',
  MAILER_SMTP_PASSWORD = 'MAILER_SMTP_PASSWORD',
  MAILER_TLS_REJECT_UNAUTHORIZED = 'MAILER_TLS_REJECT_UNAUTHORIZED',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_SCOPE = 'GOOGLE_SCOPE',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
  GITHUB_SCOPE = 'GITHUB_SCOPE',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',
  MICROSOFT_CALLBACK_URL = 'MICROSOFT_CALLBACK_URL',
  MICROSOFT_SCOPE = 'MICROSOFT_SCOPE',
  MICROSOFT_TENANT = 'MICROSOFT_TENANT',
  MICROSOFT_PROMPT = 'MICROSOFT_PROMPT',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',

  ALLOW_ANALYTICS_COLLECTION = 'ALLOW_ANALYTICS_COLLECTION',
  ANALYTICS_USER_ID = 'ANALYTICS_USER_ID',
  IS_FIRST_TIME_INFRA_SETUP = 'IS_FIRST_TIME_INFRA_SETUP',
}
