export enum InfraConfigEnum {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',

  IS_FIRST_TIME_INFRA_SETUP = 'IS_FIRST_TIME_INFRA_SETUP',
}

export enum InfraConfigEnumForClient {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',

  IS_FIRST_TIME_INFRA_SETUP = 'IS_FIRST_TIME_INFRA_SETUP',
}
