export enum InfraConfigEnum {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',

  SAML_ISSUER = 'SAML_ISSUER',
  SAML_AUDIENCE = 'SAML_AUDIENCE',
  SAML_CALLBACK_URL = 'SAML_CALLBACK_URL',
  SAML_CERT = 'SAML_CERT',
  SAML_ENTRY_POINT = 'SAML_ENTRY_POINT',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',
}
