// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../../hoppscotch-sh-admin/src/components/app/Header.vue')['default']
    AppLogin: typeof import('./../../hoppscotch-sh-admin/src/components/app/Login.vue')['default']
    AppLogout: typeof import('./../../hoppscotch-sh-admin/src/components/app/Logout.vue')['default']
    AppModal: typeof import('./../../hoppscotch-sh-admin/src/components/app/Modal.vue')['default']
    AppSidebar: typeof import('./../../hoppscotch-sh-admin/src/components/app/Sidebar.vue')['default']
    AppToast: typeof import('./../../hoppscotch-sh-admin/src/components/app/Toast.vue')['default']
    DashboardMetricsCard: typeof import('./../../hoppscotch-sh-admin/src/components/dashboard/MetricsCard.vue')['default']
    HoppButtonPrimary: typeof import('@hoppscotch/ui')['HoppButtonPrimary']
    HoppButtonSecondary: typeof import('@hoppscotch/ui')['HoppButtonSecondary']
    HoppSmartCheckbox: typeof import('@hoppscotch/ui')['HoppSmartCheckbox']
    HoppSmartConfirmModal: typeof import('@hoppscotch/ui')['HoppSmartConfirmModal']
    HoppSmartInput: typeof import('@hoppscotch/ui')['HoppSmartInput']
    HoppSmartIntersection: typeof import('@hoppscotch/ui')['HoppSmartIntersection']
    HoppSmartItem: typeof import('@hoppscotch/ui')['HoppSmartItem']
    HoppSmartLink: typeof import('@hoppscotch/ui')['HoppSmartLink']
    HoppSmartModal: typeof import('@hoppscotch/ui')['HoppSmartModal']
    HoppSmartPicture: typeof import('@hoppscotch/ui')['HoppSmartPicture']
    HoppSmartPlaceholder: typeof import('@hoppscotch/ui')['HoppSmartPlaceholder']
    HoppSmartSelectWrapper: typeof import('@hoppscotch/ui')['HoppSmartSelectWrapper']
    HoppSmartSpinner: typeof import('@hoppscotch/ui')['HoppSmartSpinner']
    HoppSmartTab: typeof import('@hoppscotch/ui')['HoppSmartTab']
    HoppSmartTabs: typeof import('@hoppscotch/ui')['HoppSmartTabs']
    HoppSmartToggle: typeof import('@hoppscotch/ui')['HoppSmartToggle']
    IconLucideHelpCircle: typeof import('~icons/lucide/help-circle')['default']
    SettingsAuthProvider: typeof import('./../../hoppscotch-sh-admin/src/components/settings/AuthProvider.vue')['default']
    SettingsComponent: typeof import('./../../hoppscotch-sh-admin/src/components/settings/Component.vue')['default']
    SettingsConfigurations: typeof import('./../../hoppscotch-sh-admin/src/components/settings/Configurations.vue')['default']
    SettingsDataSharing: typeof import('./../../hoppscotch-sh-admin/src/components/settings/DataSharing.vue')['default']
    SettingsReset: typeof import('./../../hoppscotch-sh-admin/src/components/settings/Reset.vue')['default']
    SettingsServerRestart: typeof import('./../../hoppscotch-sh-admin/src/components/settings/ServerRestart.vue')['default']
    SettingsSmtpConfiguration: typeof import('./../../hoppscotch-sh-admin/src/components/settings/SmtpConfiguration.vue')['default']
    SetupDataSharingAndNewsletter: typeof import('./../../hoppscotch-sh-admin/src/components/setup/DataSharingAndNewsletter.vue')['default']
    TeamsAdd: typeof import('./../../hoppscotch-sh-admin/src/components/teams/Add.vue')['default']
    TeamsDetails: typeof import('./../../hoppscotch-sh-admin/src/components/teams/Details.vue')['default']
    TeamsInvite: typeof import('./../../hoppscotch-sh-admin/src/components/teams/Invite.vue')['default']
    TeamsMembers: typeof import('./../../hoppscotch-sh-admin/src/components/teams/Members.vue')['default']
    TeamsPendingInvites: typeof import('./../../hoppscotch-sh-admin/src/components/teams/PendingInvites.vue')['default']
    Tippy: typeof import('vue-tippy')['Tippy']
    Tokens: typeof import('./../../hoppscotch-sh-admin/src/components/tokens/index.vue')['default']
    TokensGenerateModal: typeof import('./../../hoppscotch-sh-admin/src/components/tokens/GenerateModal.vue')['default']
    TokensList: typeof import('./../../hoppscotch-sh-admin/src/components/tokens/List.vue')['default']
    TokensOverview: typeof import('./../../hoppscotch-sh-admin/src/components/tokens/Overview.vue')['default']
    UiAutoResetIcon: typeof import('./../../hoppscotch-sh-admin/src/components/ui/AutoResetIcon.vue')['default']
    UsersDetails: typeof import('./../../hoppscotch-sh-admin/src/components/users/Details.vue')['default']
    UsersInviteModal: typeof import('./../../hoppscotch-sh-admin/src/components/users/InviteModal.vue')['default']
    UsersSharedRequests: typeof import('./../../hoppscotch-sh-admin/src/components/users/SharedRequests.vue')['default']
    UsersSuccessInviteModal: typeof import('./../../hoppscotch-sh-admin/src/components/users/SuccessInviteModal.vue')['default']
  }

}
