import vue from "@vitejs/plugin-vue"
import dts from "vite-plugin-dts"
import path from "path"
import Icons from "unplugin-icons/vite"
import { defineConfig } from "vite"
import WindiCSS from "vite-plugin-windicss"

export default defineConfig({
  plugins: [
    vue(),
    dts({
      insertTypesEntry: true,
      skipDiagnostics: true,
      outputDir: ['dist']
    }),
    WindiCSS({
      root: path.resolve(__dirname),
    }),
    Icons({
      compiler: "vue3"
    }),
  ], // to process SFC
  build: {
    sourcemap: true,
    minify: false,
    lib: {
      entry: {
        "plugin": path.resolve(__dirname, "src/plugin.ts"),
        "components": path.resolve(__dirname, "src/components/index.ts"),
      },
      name: "hopp-ui",
      formats: ["es"],
      fileName: (format, entry) => `${entry}.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into HoppUI library
      external: ["vue", "vue-router"], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: "named",
      },
    },
    emptyOutDir: true, // to retain the types folder generated by tsc
  },
})
