// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./components/button/Primary.vue')['default']
    ButtonSecondary: typeof import('./components/button/Secondary.vue')['default']
    IconLucideLoader: typeof import('~icons/lucide/loader')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartAnchor: typeof import('./components/smart/Anchor.vue')['default']
    SmartAutoComplete: typeof import('./components/smart/AutoComplete.vue')['default']
    SmartCheckbox: typeof import('./components/smart/Checkbox.vue')['default']
    SmartConfirmModal: typeof import('./components/smart/ConfirmModal.vue')['default']
    SmartExpand: typeof import('./components/smart/Expand.vue')['default']
    SmartFileChip: typeof import('./components/smart/FileChip.vue')['default']
    SmartIntersection: typeof import('./components/smart/Intersection.vue')['default']
    SmartItem: typeof import('./components/smart/Item.vue')['default']
    SmartLink: typeof import('./components/smart/Link.vue')['default']
    SmartModal: typeof import('./components/smart/Modal.vue')['default']
    SmartProgressRing: typeof import('./components/smart/ProgressRing.vue')['default']
    SmartRadio: typeof import('./components/smart/Radio.vue')['default']
    SmartRadioGroup: typeof import('./components/smart/RadioGroup.vue')['default']
    SmartSlideOver: typeof import('./components/smart/SlideOver.vue')['default']
    SmartSpinner: typeof import('./components/smart/Spinner.vue')['default']
    SmartTab: typeof import('./components/smart/Tab.vue')['default']
    SmartTabs: typeof import('./components/smart/Tabs.vue')['default']
    SmartToggle: typeof import('./components/smart/Toggle.vue')['default']
    SmartWindow: typeof import('./components/smart/Window.vue')['default']
    SmartWindows: typeof import('./components/smart/Windows.vue')['default']
  }

}
