import AppAnnouncement from "./components/app/Announcement.vue";
import AppFooter from "./components/app/Footer.vue";
import AppFuse from "./components/app/Fuse.vue";
import AppGitHubStarButton from "./components/app/GitHubStarButton.vue";
import AppHeader from "./components/app/Header.vue";
import AppLogo from "./components/app/Logo.vue";
import AppPowerSearch from "./components/app/PowerSearch.vue";
import AppPowerSearchEntry from "./components/app/PowerSearchEntry.vue";
import AppSection from "./components/app/Section.vue";
import AppShare from "./components/app/Share.vue";
import AppShortcuts from "./components/app/Shortcuts.vue";
import AppShortcutsEntry from "./components/app/ShortcutsEntry.vue";
import AppSidenav from "./components/app/Sidenav.vue";
import AppSlideOver from "./components/app/SlideOver.vue";
import AppSupport from "./components/app/Support.vue";
import ButtonPrimary from "./components/button/Primary.vue";
import ButtonSecondary from "./components/button/Secondary.vue";
import CollectionsAdd from "./components/collections/Add.vue";
import CollectionsAddFolder from "./components/collections/AddFolder.vue";
import CollectionsChooseType from "./components/collections/ChooseType.vue";
import CollectionsEdit from "./components/collections/Edit.vue";
import CollectionsEditFolder from "./components/collections/EditFolder.vue";
import CollectionsEditRequest from "./components/collections/EditRequest.vue";
import CollectionsImportExport from "./components/collections/ImportExport.vue";
import CollectionsSaveRequest from "./components/collections/SaveRequest.vue";
import CollectionsGraphqlAdd from "./components/collections/graphql/Add.vue";
import CollectionsGraphqlAddFolder from "./components/collections/graphql/AddFolder.vue";
import CollectionsGraphqlCollection from "./components/collections/graphql/Collection.vue";
import CollectionsGraphqlEdit from "./components/collections/graphql/Edit.vue";
import CollectionsGraphqlEditFolder from "./components/collections/graphql/EditFolder.vue";
import CollectionsGraphqlEditRequest from "./components/collections/graphql/EditRequest.vue";
import CollectionsGraphqlFolder from "./components/collections/graphql/Folder.vue";
import CollectionsGraphqlImportExport from "./components/collections/graphql/ImportExport.vue";
import CollectionsGraphqlRequest from "./components/collections/graphql/Request.vue";
import CollectionsGraphql from "./components/collections/graphql/index.vue";
import Collections from "./components/collections/index.vue";
import CollectionsMyCollection from "./components/collections/my/Collection.vue";
import CollectionsMyFolder from "./components/collections/my/Folder.vue";
import CollectionsMyRequest from "./components/collections/my/Request.vue";
import CollectionsTeamsCollection from "./components/collections/teams/Collection.vue";
import CollectionsTeamsFolder from "./components/collections/teams/Folder.vue";
import CollectionsTeamsRequest from "./components/collections/teams/Request.vue";
import DocsCollection from "./components/docs/Collection.vue";
import DocsFolder from "./components/docs/Folder.vue";
import DocsRequest from "./components/docs/Request.vue";
import EnvironmentsAdd from "./components/environments/Add.vue";
import EnvironmentsEdit from "./components/environments/Edit.vue";
import EnvironmentsEnvironment from "./components/environments/Environment.vue";
import EnvironmentsImportExport from "./components/environments/ImportExport.vue";
import Environments from "./components/environments/index.vue";
import FirebaseLogin from "./components/firebase/Login.vue";
import FirebaseLogout from "./components/firebase/Logout.vue";
import GraphqlField from "./components/graphql/Field.vue";
import GraphqlQueryEditor from "./components/graphql/QueryEditor.vue";
import GraphqlRequest from "./components/graphql/Request.vue";
import GraphqlRequestOptions from "./components/graphql/RequestOptions.vue";
import GraphqlResponse from "./components/graphql/Response.vue";
import GraphqlSidebar from "./components/graphql/Sidebar.vue";
import GraphqlType from "./components/graphql/Type.vue";
import GraphqlTypeLink from "./components/graphql/TypeLink.vue";
import HistoryGraphqlCard from "./components/history/graphql/Card.vue";
import History from "./components/history/index.vue";
import HistoryRestCard from "./components/history/rest/Card.vue";
import HttpAuthorization from "./components/http/Authorization.vue";
import HttpBody from "./components/http/Body.vue";
import HttpBodyParameters from "./components/http/BodyParameters.vue";
import HttpCodegenModal from "./components/http/CodegenModal.vue";
import HttpHeaders from "./components/http/Headers.vue";
import HttpImportCurl from "./components/http/ImportCurl.vue";
import HttpOAuth2Authorization from "./components/http/OAuth2Authorization.vue";
import HttpParameters from "./components/http/Parameters.vue";
import HttpPreRequestScript from "./components/http/PreRequestScript.vue";
import HttpRawBody from "./components/http/RawBody.vue";
import HttpRequest from "./components/http/Request.vue";
import HttpResponse from "./components/http/Response.vue";
import HttpResponseMeta from "./components/http/ResponseMeta.vue";
import HttpTestResult from "./components/http/TestResult.vue";
import HttpTestResultEntry from "./components/http/TestResultEntry.vue";
import HttpTestResultReport from "./components/http/TestResultReport.vue";
import HttpTests from "./components/http/Tests.vue";
import LandingCTA from "./components/landing/CTA.vue";
import LandingFeatures from "./components/landing/Features.vue";
import LandingFooter from "./components/landing/Footer.vue";
import LandingHero from "./components/landing/Hero.vue";
import LandingScreenshot from "./components/landing/Screenshot.vue";
import LandingStats from "./components/landing/Stats.vue";
import LandingUsers from "./components/landing/Users.vue";
import LensesHeadersRenderer from "./components/lenses/HeadersRenderer.vue";
import LensesResponseBodyRenderer from "./components/lenses/ResponseBodyRenderer.vue";
import LensesRenderersHTMLLensRenderer from "./components/lenses/renderers/HTMLLensRenderer.vue";
import LensesRenderersImageLensRenderer from "./components/lenses/renderers/ImageLensRenderer.vue";
import LensesRenderersJSONLensRenderer from "./components/lenses/renderers/JSONLensRenderer.vue";
import LensesRenderersRawLensRenderer from "./components/lenses/renderers/RawLensRenderer.vue";
import LensesRenderersXMLLensRenderer from "./components/lenses/renderers/XMLLensRenderer.vue";
import ProfilePicture from "./components/profile/Picture.vue";
import RealtimeLog from "./components/realtime/Log.vue";
import RealtimeMqtt from "./components/realtime/Mqtt.vue";
import RealtimeSocketio from "./components/realtime/Socketio.vue";
import RealtimeSse from "./components/realtime/Sse.vue";
import RealtimeWebsocket from "./components/realtime/Websocket.vue";
import SmartAccentModePicker from "./components/smart/AccentModePicker.vue";
import SmartAceEditor from "./components/smart/AceEditor.vue";
import SmartAnchor from "./components/smart/Anchor.vue";
import SmartAutoComplete from "./components/smart/AutoComplete.vue";
import SmartChangeLanguage from "./components/smart/ChangeLanguage.vue";
import SmartColorModePicker from "./components/smart/ColorModePicker.vue";
import SmartConfirmModal from "./components/smart/ConfirmModal.vue";
import SmartDeletableChip from "./components/smart/DeletableChip.vue";
import SmartEnvInput from "./components/smart/EnvInput.vue";
import SmartFontSizePicker from "./components/smart/FontSizePicker.vue";
import SmartIcon from "./components/smart/Icon.vue";
import SmartIntersection from "./components/smart/Intersection.vue";
import SmartItem from "./components/smart/Item.vue";
import SmartJsEditor from "./components/smart/JsEditor.vue";
import SmartLoadingIndicator from "./components/smart/LoadingIndicator.vue";
import SmartModal from "./components/smart/Modal.vue";
import SmartProgressRing from "./components/smart/ProgressRing.vue";
import SmartSpinner from "./components/smart/Spinner.vue";
import SmartTab from "./components/smart/Tab.vue";
import SmartTabs from "./components/smart/Tabs.vue";
import SmartToggle from "./components/smart/Toggle.vue";
import TabPrimary from "./components/tab/Primary.vue";
import TabSecondary from "./components/tab/Secondary.vue";
import TeamsAdd from "./components/teams/Add.vue";
import TeamsEdit from "./components/teams/Edit.vue";
import TeamsTeam from "./components/teams/Team.vue";
import Teams from "./components/teams/index.vue";
declare global {
    interface __VLS_GlobalComponents {
        AppAnnouncement: typeof AppAnnouncement;
        AppFooter: typeof AppFooter;
        AppFuse: typeof AppFuse;
        AppGitHubStarButton: typeof AppGitHubStarButton;
        AppHeader: typeof AppHeader;
        AppLogo: typeof AppLogo;
        AppPowerSearch: typeof AppPowerSearch;
        AppPowerSearchEntry: typeof AppPowerSearchEntry;
        AppSection: typeof AppSection;
        AppShare: typeof AppShare;
        AppShortcuts: typeof AppShortcuts;
        AppShortcutsEntry: typeof AppShortcutsEntry;
        AppSidenav: typeof AppSidenav;
        AppSlideOver: typeof AppSlideOver;
        AppSupport: typeof AppSupport;
        ButtonPrimary: typeof ButtonPrimary;
        ButtonSecondary: typeof ButtonSecondary;
        CollectionsAdd: typeof CollectionsAdd;
        CollectionsAddFolder: typeof CollectionsAddFolder;
        CollectionsChooseType: typeof CollectionsChooseType;
        CollectionsEdit: typeof CollectionsEdit;
        CollectionsEditFolder: typeof CollectionsEditFolder;
        CollectionsEditRequest: typeof CollectionsEditRequest;
        CollectionsImportExport: typeof CollectionsImportExport;
        CollectionsSaveRequest: typeof CollectionsSaveRequest;
        CollectionsGraphqlAdd: typeof CollectionsGraphqlAdd;
        CollectionsGraphqlAddFolder: typeof CollectionsGraphqlAddFolder;
        CollectionsGraphqlCollection: typeof CollectionsGraphqlCollection;
        CollectionsGraphqlEdit: typeof CollectionsGraphqlEdit;
        CollectionsGraphqlEditFolder: typeof CollectionsGraphqlEditFolder;
        CollectionsGraphqlEditRequest: typeof CollectionsGraphqlEditRequest;
        CollectionsGraphqlFolder: typeof CollectionsGraphqlFolder;
        CollectionsGraphqlImportExport: typeof CollectionsGraphqlImportExport;
        CollectionsGraphqlRequest: typeof CollectionsGraphqlRequest;
        CollectionsGraphql: typeof CollectionsGraphql;
        Collections: typeof Collections;
        CollectionsMyCollection: typeof CollectionsMyCollection;
        CollectionsMyFolder: typeof CollectionsMyFolder;
        CollectionsMyRequest: typeof CollectionsMyRequest;
        CollectionsTeamsCollection: typeof CollectionsTeamsCollection;
        CollectionsTeamsFolder: typeof CollectionsTeamsFolder;
        CollectionsTeamsRequest: typeof CollectionsTeamsRequest;
        DocsCollection: typeof DocsCollection;
        DocsFolder: typeof DocsFolder;
        DocsRequest: typeof DocsRequest;
        EnvironmentsAdd: typeof EnvironmentsAdd;
        EnvironmentsEdit: typeof EnvironmentsEdit;
        EnvironmentsEnvironment: typeof EnvironmentsEnvironment;
        EnvironmentsImportExport: typeof EnvironmentsImportExport;
        Environments: typeof Environments;
        FirebaseLogin: typeof FirebaseLogin;
        FirebaseLogout: typeof FirebaseLogout;
        GraphqlField: typeof GraphqlField;
        GraphqlQueryEditor: typeof GraphqlQueryEditor;
        GraphqlRequest: typeof GraphqlRequest;
        GraphqlRequestOptions: typeof GraphqlRequestOptions;
        GraphqlResponse: typeof GraphqlResponse;
        GraphqlSidebar: typeof GraphqlSidebar;
        GraphqlType: typeof GraphqlType;
        GraphqlTypeLink: typeof GraphqlTypeLink;
        HistoryGraphqlCard: typeof HistoryGraphqlCard;
        History: typeof History;
        HistoryRestCard: typeof HistoryRestCard;
        HttpAuthorization: typeof HttpAuthorization;
        HttpBody: typeof HttpBody;
        HttpBodyParameters: typeof HttpBodyParameters;
        HttpCodegenModal: typeof HttpCodegenModal;
        HttpHeaders: typeof HttpHeaders;
        HttpImportCurl: typeof HttpImportCurl;
        HttpOAuth2Authorization: typeof HttpOAuth2Authorization;
        HttpParameters: typeof HttpParameters;
        HttpPreRequestScript: typeof HttpPreRequestScript;
        HttpRawBody: typeof HttpRawBody;
        HttpRequest: typeof HttpRequest;
        HttpResponse: typeof HttpResponse;
        HttpResponseMeta: typeof HttpResponseMeta;
        HttpTestResult: typeof HttpTestResult;
        HttpTestResultEntry: typeof HttpTestResultEntry;
        HttpTestResultReport: typeof HttpTestResultReport;
        HttpTests: typeof HttpTests;
        LandingCTA: typeof LandingCTA;
        LandingFeatures: typeof LandingFeatures;
        LandingFooter: typeof LandingFooter;
        LandingHero: typeof LandingHero;
        LandingScreenshot: typeof LandingScreenshot;
        LandingStats: typeof LandingStats;
        LandingUsers: typeof LandingUsers;
        LensesHeadersRenderer: typeof LensesHeadersRenderer;
        LensesResponseBodyRenderer: typeof LensesResponseBodyRenderer;
        LensesRenderersHTMLLensRenderer: typeof LensesRenderersHTMLLensRenderer;
        LensesRenderersImageLensRenderer: typeof LensesRenderersImageLensRenderer;
        LensesRenderersJSONLensRenderer: typeof LensesRenderersJSONLensRenderer;
        LensesRenderersRawLensRenderer: typeof LensesRenderersRawLensRenderer;
        LensesRenderersXMLLensRenderer: typeof LensesRenderersXMLLensRenderer;
        ProfilePicture: typeof ProfilePicture;
        RealtimeLog: typeof RealtimeLog;
        RealtimeMqtt: typeof RealtimeMqtt;
        RealtimeSocketio: typeof RealtimeSocketio;
        RealtimeSse: typeof RealtimeSse;
        RealtimeWebsocket: typeof RealtimeWebsocket;
        SmartAccentModePicker: typeof SmartAccentModePicker;
        SmartAceEditor: typeof SmartAceEditor;
        SmartAnchor: typeof SmartAnchor;
        SmartAutoComplete: typeof SmartAutoComplete;
        SmartChangeLanguage: typeof SmartChangeLanguage;
        SmartColorModePicker: typeof SmartColorModePicker;
        SmartConfirmModal: typeof SmartConfirmModal;
        SmartDeletableChip: typeof SmartDeletableChip;
        SmartEnvInput: typeof SmartEnvInput;
        SmartFontSizePicker: typeof SmartFontSizePicker;
        SmartIcon: typeof SmartIcon;
        SmartIntersection: typeof SmartIntersection;
        SmartItem: typeof SmartItem;
        SmartJsEditor: typeof SmartJsEditor;
        SmartLoadingIndicator: typeof SmartLoadingIndicator;
        SmartModal: typeof SmartModal;
        SmartProgressRing: typeof SmartProgressRing;
        SmartSpinner: typeof SmartSpinner;
        SmartTab: typeof SmartTab;
        SmartTabs: typeof SmartTabs;
        SmartToggle: typeof SmartToggle;
        TabPrimary: typeof TabPrimary;
        TabSecondary: typeof TabSecondary;
        TeamsAdd: typeof TeamsAdd;
        TeamsEdit: typeof TeamsEdit;
        TeamsTeam: typeof TeamsTeam;
        Teams: typeof Teams;
    }
}
