// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    Carbon3dCursor: typeof import("~icons/carbon/3d-cursor")["default"]
    CarbonArrowUpRight: typeof import("~icons/carbon/arrow-up-right")["default"]
    CarbonCampsite: typeof import("~icons/carbon/campsite")["default"]
    CarbonCircleDash: typeof import("~icons/carbon/circle-dash")["default"]
    CarbonDicomOverlay: typeof import("~icons/carbon/dicom-overlay")["default"]
    CarbonHome: typeof import("~icons/carbon/home")["default"]
    CarbonLanguage: typeof import("~icons/carbon/language")["default"]
    CarbonLogoGithub: typeof import("~icons/carbon/logo-github")["default"]
    CarbonMoon: typeof import("~icons/carbon/moon")["default"]
    CarbonPedestrian: typeof import("~icons/carbon/pedestrian")["default"]
    CarbonSun: typeof import("~icons/carbon/sun")["default"]
    CarbonWarning: typeof import("~icons/carbon/warning")["default"]
    Footer: typeof import("./components/Footer.vue")["default"]
    Header: typeof import("./components/Header.vue")["default"]
    README: typeof import("./components/README.md")["default"]
    Request: typeof import("./components/Request.vue")["default"]
    "Request copy": typeof import("./components/Response.vueue")["default"]
    RequestOptions: typeof import("./components/RequestOptions.vue")["default"]
    Response: typeof import("./components/Response.vue")["default"]
    Spinner: typeof import("./components/Spinner.vue")["default"]
  }
}

export { }
