// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/app/Header.vue')['default']
    AppLogin: typeof import('./components/app/Login.vue')['default']
    AppLogout: typeof import('./components/app/Logout.vue')['default']
    AppModal: typeof import('./components/app/Modal.vue')['default']
    AppSidebar: typeof import('./components/app/Sidebar.vue')['default']
    AppToast: typeof import('./components/app/Toast.vue')['default']
    ButtonPrimary: typeof import('./../../hoppscotch-ui/src/components/button/Primary.vue')['default']
    ButtonSecondary: typeof import('./../../hoppscotch-ui/src/components/button/Secondary.vue')['default']
    DashboardMetricsCard: typeof import('./components/dashboard/MetricsCard.vue')['default']
    HoppButtonPrimary: typeof import('@hoppscotch/ui')['HoppButtonPrimary']
    HoppButtonSecondary: typeof import('@hoppscotch/ui')['HoppButtonSecondary']
    HoppSmartAnchor: typeof import('@hoppscotch/ui')['HoppSmartAnchor']
    HoppSmartAutoComplete: typeof import('@hoppscotch/ui')['HoppSmartAutoComplete']
    HoppSmartConfirmModal: typeof import('@hoppscotch/ui')['HoppSmartConfirmModal']
    HoppSmartInput: typeof import('@hoppscotch/ui')['HoppSmartInput']
    HoppSmartItem: typeof import('@hoppscotch/ui')['HoppSmartItem']
    HoppSmartModal: typeof import('@hoppscotch/ui')['HoppSmartModal']
    HoppSmartPicture: typeof import('@hoppscotch/ui')['HoppSmartPicture']
    HoppSmartSpinner: typeof import('@hoppscotch/ui')['HoppSmartSpinner']
    HoppSmartTab: typeof import('@hoppscotch/ui')['HoppSmartTab']
    HoppSmartTable: typeof import('@hoppscotch/ui')['HoppSmartTable']
    HoppSmartTabs: typeof import('@hoppscotch/ui')['HoppSmartTabs']
    HoppSmartToggle: typeof import('@hoppscotch/ui')['HoppSmartToggle']
    IconLucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideInbox: typeof import('~icons/lucide/inbox')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    SettingsAuthProvider: typeof import('./components/settings/AuthProvider.vue')['default']
    SettingsConfigurations: typeof import('./components/settings/Configurations.vue')['default']
    SettingsReset: typeof import('./components/settings/Reset.vue')['default']
    SettingsServerRestart: typeof import('./components/settings/ServerRestart.vue')['default']
    SettingsSmtpConfiguration: typeof import('./components/settings/SmtpConfiguration.vue')['default']
    SmartAnchor: typeof import('./../../hoppscotch-ui/src/components/smart/Anchor.vue')['default']
    SmartAutoComplete: typeof import('./../../hoppscotch-ui/src/components/smart/AutoComplete.vue')['default']
    SmartCheckbox: typeof import('./../../hoppscotch-ui/src/components/smart/Checkbox.vue')['default']
    SmartConfirmModal: typeof import('./../../hoppscotch-ui/src/components/smart/ConfirmModal.vue')['default']
    SmartExpand: typeof import('./../../hoppscotch-ui/src/components/smart/Expand.vue')['default']
    SmartFileChip: typeof import('./../../hoppscotch-ui/src/components/smart/FileChip.vue')['default']
    SmartInput: typeof import('./../../hoppscotch-ui/src/components/smart/Input.vue')['default']
    SmartIntersection: typeof import('./../../hoppscotch-ui/src/components/smart/Intersection.vue')['default']
    SmartItem: typeof import('./../../hoppscotch-ui/src/components/smart/Item.vue')['default']
    SmartLink: typeof import('./../../hoppscotch-ui/src/components/smart/Link.vue')['default']
    SmartModal: typeof import('./../../hoppscotch-ui/src/components/smart/Modal.vue')['default']
    SmartPicture: typeof import('./../../hoppscotch-ui/src/components/smart/Picture.vue')['default']
    SmartPlaceholder: typeof import('./../../hoppscotch-ui/src/components/smart/Placeholder.vue')['default']
    SmartProgressRing: typeof import('./../../hoppscotch-ui/src/components/smart/ProgressRing.vue')['default']
    SmartRadio: typeof import('./../../hoppscotch-ui/src/components/smart/Radio.vue')['default']
    SmartRadioGroup: typeof import('./../../hoppscotch-ui/src/components/smart/RadioGroup.vue')['default']
    SmartSelectWrapper: typeof import('./../../hoppscotch-ui/src/components/smart/SelectWrapper.vue')['default']
    SmartSlideOver: typeof import('./../../hoppscotch-ui/src/components/smart/SlideOver.vue')['default']
    SmartSpinner: typeof import('./../../hoppscotch-ui/src/components/smart/Spinner.vue')['default']
    SmartTab: typeof import('./../../hoppscotch-ui/src/components/smart/Tab.vue')['default']
    SmartTable: typeof import('./../../hoppscotch-ui/src/components/smart/Table.vue')['default']
    SmartTabs: typeof import('./../../hoppscotch-ui/src/components/smart/Tabs.vue')['default']
    SmartToggle: typeof import('./../../hoppscotch-ui/src/components/smart/Toggle.vue')['default']
    SmartTree: typeof import('./../../hoppscotch-ui/src/components/smart/Tree.vue')['default']
    SmartTreeBranch: typeof import('./../../hoppscotch-ui/src/components/smart/TreeBranch.vue')['default']
    SmartWindow: typeof import('./../../hoppscotch-ui/src/components/smart/Window.vue')['default']
    SmartWindows: typeof import('./../../hoppscotch-ui/src/components/smart/Windows.vue')['default']
    TeamsAdd: typeof import('./components/teams/Add.vue')['default']
    TeamsDetails: typeof import('./components/teams/Details.vue')['default']
    TeamsInvite: typeof import('./components/teams/Invite.vue')['default']
    TeamsMembers: typeof import('./components/teams/Members.vue')['default']
    TeamsPendingInvites: typeof import('./components/teams/PendingInvites.vue')['default']
    Tippy: typeof import('vue-tippy')['Tippy']
    UiAutoResetIcon: typeof import('./components/ui/AutoResetIcon.vue')['default']
    UsersDetails: typeof import('./components/users/Details.vue')['default']
    UsersInviteModal: typeof import('./components/users/InviteModal.vue')['default']
    UsersSharedRequests: typeof import('./components/users/SharedRequests.vue')['default']
    AppHeader: typeof import('./components/app/Header.vue')['default'];
    AppLogin: typeof import('./components/app/Login.vue')['default'];
    AppLogout: typeof import('./components/app/Logout.vue')['default'];
    AppModal: typeof import('./components/app/Modal.vue')['default'];
    AppSidebar: typeof import('./components/app/Sidebar.vue')['default'];
    AppToast: typeof import('./components/app/Toast.vue')['default'];
    DashboardMetricsCard: typeof import('./components/dashboard/MetricsCard.vue')['default'];
    HoppButtonSecondary: typeof import('@hoppscotch/ui')['HoppButtonSecondary'];
    HoppSmartAnchor: typeof import('@hoppscotch/ui')['HoppSmartAnchor'];
    HoppSmartConfirmModal: typeof import('@hoppscotch/ui')['HoppSmartConfirmModal'];
    HoppSmartInput: typeof import('@hoppscotch/ui')['HoppSmartInput'];
    HoppSmartItem: typeof import('@hoppscotch/ui')['HoppSmartItem'];
    HoppSmartPicture: typeof import('@hoppscotch/ui')['HoppSmartPicture'];
    HoppSmartSpinner: typeof import('@hoppscotch/ui')['HoppSmartSpinner'];
    IconLucideInbox: typeof import('~icons/lucide/inbox')['default'];
    TeamsAdd: typeof import('./components/teams/Add.vue')['default'];
    TeamsDetails: typeof import('./components/teams/Details.vue')['default'];
    TeamsInvite: typeof import('./components/teams/Invite.vue')['default'];
    TeamsMembers: typeof import('./components/teams/Members.vue')['default'];
    TeamsPendingInvites: typeof import('./components/teams/PendingInvites.vue')['default'];
    Tippy: typeof import('vue-tippy')['Tippy'];
    UsersInviteModal: typeof import('./components/users/InviteModal.vue')['default'];
  }
}
