// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/app/Header.vue')['default']
    AppLogin: typeof import('./components/app/Login.vue')['default']
    AppLogout: typeof import('./components/app/Logout.vue')['default']
    AppModal: typeof import('./components/app/Modal.vue')['default']
    AppSidebar: typeof import('./components/app/Sidebar.vue')['default']
    AppToast: typeof import('./components/app/Toast.vue')['default']
    HoppButtonPrimary: typeof import('@hoppscotch/ui')['HoppButtonPrimary']
    HoppButtonSecondary: typeof import('@hoppscotch/ui')['HoppButtonSecondary']
    HoppSmartAnchor: typeof import('@hoppscotch/ui')['HoppSmartAnchor']
    HoppSmartConfirmModal: typeof import('@hoppscotch/ui')['HoppSmartConfirmModal']
    HoppSmartItem: typeof import('@hoppscotch/ui')['HoppSmartItem']
    HoppSmartModal: typeof import('@hoppscotch/ui')['HoppSmartModal']
    HoppSmartSpinner: typeof import('@hoppscotch/ui')['HoppSmartSpinner']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideInbox: typeof import('~icons/lucide/inbox')['default']
    IconLucideLayoutDashboard: typeof import('~icons/lucide/layout-dashboard')['default']
    IconLucideMenu: typeof import('~icons/lucide/menu')['default']
    IconLucideMoreHorizontal: typeof import('~icons/lucide/more-horizontal')['default']
    IconLucideSidebarClose: typeof import('~icons/lucide/sidebar-close')['default']
    IconLucideSidebarOpen: typeof import('~icons/lucide/sidebar-open')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    IconLucideUsers: typeof import('~icons/lucide/users')['default']
    ProfilePicture: typeof import('./components/profile/Picture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamsAddMembers: typeof import('./components/teams/AddMembers.vue')['default']
  }

}
