// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/app/Header.vue')['default']
    AppLogin: typeof import('./components/app/Login.vue')['default']
    AppLogout: typeof import('./components/app/Logout.vue')['default']
    AppModal: typeof import('./components/app/Modal.vue')['default']
    AppSidebar: typeof import('./components/app/Sidebar.vue')['default']
    AppToast: typeof import('./components/app/Toast.vue')['default']
    ProfilePicture: typeof import('./components/profile/Picture.vue')['default']
    TeamsAddMembers: typeof import('./components/teams/AddMembers.vue')['default']
    TeamsDetails: typeof import('./components/teams/Details.vue')['default']
    TeamsInvite: typeof import('./components/teams/Invite.vue')['default']
    TeamsMembers: typeof import('./components/teams/Members.vue')['default']
    TeamsPendingInvites: typeof import('./components/teams/PendingInvites.vue')['default']
    Tippy: typeof import('vue-tippy')['Tippy']
  }

}
