/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HoppButtonPrimary: typeof import('@hoppscotch/ui')['HoppButtonPrimary']
    HoppSmartItem: typeof import('@hoppscotch/ui')['HoppSmartItem']
    LayoutHeader: typeof import('./components/layout/LayoutHeader.vue')['default']
    LayoutSidebar: typeof import('./components/layout/LayoutSidebar.vue')['default']
    Tippy: typeof import('vue-tippy')['Tippy']
  }
}
