/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormHeader: typeof import('./components/url/FormHeader.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HoppButtonPrimary: typeof import('@hoppscotch/ui')['HoppButtonPrimary']
    HoppButtonSecondary: typeof import('@hoppscotch/ui')['HoppButtonSecondary']
    HoppSmartAnchor: typeof import('@hoppscotch/ui')['HoppSmartAnchor']
    HoppSmartInput: typeof import('@hoppscotch/ui')['HoppSmartInput']
    HoppSmartItem: typeof import('@hoppscotch/ui')['HoppSmartItem']
    HoppSmartLink: typeof import('@hoppscotch/ui')['HoppSmartLink']
    HoppSmartSpinner: typeof import('@hoppscotch/ui')['HoppSmartSpinner']
    IconLucideArrowRightCircle: typeof import('~icons/lucide/arrow-right-circle')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideGlobe: typeof import('~icons/lucide/globe')['default']
    IconLucideHome: typeof import('~icons/lucide/home')['default']
    IconLucideInbox: typeof import('~icons/lucide/inbox')['default']
    IconLucideLoader2: typeof import('~icons/lucide/loader2')['default']
    IconLucideMenu: typeof import('~icons/lucide/menu')['default']
    IconLucidePin: typeof import('~icons/lucide/pin')['default']
    IconLucidePinOff: typeof import('~icons/lucide/pin-off')['default']
    IconLucideServer: typeof import('~icons/lucide/server')['default']
    IconLucideSidebarClose: typeof import('~icons/lucide/sidebar-close')['default']
    IconLucideSidebarOpen: typeof import('~icons/lucide/sidebar-open')['default']
    IconLucideTrash2: typeof import('~icons/lucide/trash2')['default']
    LayoutHeader: typeof import('./components/layout/LayoutHeader.vue')['default']
    LayoutSidebar: typeof import('./components/layout/LayoutSidebar.vue')['default']
    RecentUrlItem: typeof import('./components/url/RecentUrlItem.vue')['default']
    RecentUrlList: typeof import('./components/url/RecentUrlList.vue')['default']
    ServerUrlForm: typeof import('./components/url/ServerUrlForm.vue')['default']
    ServerUrlInput: typeof import('./components/url/ServerUrlInput.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Tippy: typeof import('vue-tippy')['Tippy']
    UpdateDialog: typeof import('./components/UpdateDialog.vue')['default']
    UrlForm: typeof import('./components/UrlForm.vue')['default']
  }
}
