[package]
name = "webapp-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.7" }
base64 = "0.22.1"
blake3 = { version = "1.5.4", features = ["serde"] }
bytes = "1.8.0"
chrono = { version = "0.4.38", features = ["serde"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "serde"] }
mime_guess = "2.0.5"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6", features = ["compression-zstd", "fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2.5.0"
zip = "2.2.0"
zstd = "0.13.2"
