-- This is a custom migration file which is not generated by Prisma.
-- The aim of this migration is to add text search indices to the TeamCollection and TeamRequest tables.

-- Create Extension
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create GIN Trigram Index for Team Collection title
CREATE INDEX
  "TeamCollection_title_trgm_idx"
ON
  "TeamCollection"
USING
  GIN (title gin_trgm_ops);

-- Create GIN Trigram Index for Team Collection title
CREATE INDEX
  "TeamRequest_title_trgm_idx"
ON
  "TeamRequest"
USING
  GIN (title gin_trgm_ops);

